### ISSUE TITLE
FOV取值多少

### ISSUE THREAD

**Issue by wqw547243068** [symmru/Dual-fisheye-video-stitching#1]
下载400m测试视频后，尝试执行以下命令
- fov = 180 

```sh
# python Fisheye_stitching.py -o output_file_path -i1 left_fisheye_video -i2 right_fisheye_video -f FOV
python Fisheye_stitching.py -o wqw_statich.mp4 -i1 data/left.mp4 -i2 data/right.mp4 -f 360 

```

错误信息:

```
successful
The count is 943
The percentage of interior points is 0.06
Traceback (most recent call last):
  File "/Users/bytedance/work/video/Dual-fisheye-video-stitching/Fisheye_stitching.py", line 578, in <module>
    stitch(cap_1=args.input_path_left,cap_2=args.input_path_right, written_path=args.output_path,fov=int(args.FOV))
  File "/Users/bytedance/work/video/Dual-fisheye-video-stitching/Fisheye_stitching.py", line 294, in stitch
    top, bottom = verticalBoundary(M_current, W_remap, W, H)
  File "/Users/bytedance/work/video/Dual-fisheye-video-stitching/Fisheye_stitching.py", line 116, in verticalBoundary
    top = np.max(
  File "<__array_function__ internals>", line 200, in amax
  File "/Users/bytedance/miniconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Users/bytedance/miniconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

请问 FOV 取值怎么设置？

**Comment by JackieZhuzzz** [comment]
We set the FOV to 194. The FOV argument represents the field-of-view of each fisheye camera.
